# Generated by Django 2.2.14 on 2021-08-11 04:31

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, verbose_name='아이디')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('registerd_date', models.DateTimeField(auto_now_add=True, verbose_name='가입시간')),
                ('image', models.ImageField(default='face-recognition.png', storage=home.models.OverwriteStorage(), upload_to='', verbose_name='이미지')),
                ('check', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '사용자 명단',
                'verbose_name_plural': '사용자 명단',
                'db_table': 'hasik_user',
            },
        ),
    ]
