# Generated by Django 2.2.14 on 2021-08-11 05:47

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210811_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='face-recognition.png', storage=home.models.OverwriteStorage(), upload_to='', verbose_name='이미지'),
        ),
    ]
