# Generated by Django 3.2.5 on 2021-08-03 18:19

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, storage=home.models.OverwriteStorage(), upload_to='', verbose_name='이미지'),
        ),
    ]
