# Generated by Django 3.2.5 on 2021-08-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
