# Generated by Django 3.2.5 on 2021-08-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_user_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registerd_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='가입시간'),
        ),
    ]
