# Generated by Django 3.2.5 on 2021-07-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=64, verbose_name='방 이름')),
                ('room_password', models.CharField(max_length=64, verbose_name='방 비밀번호')),
                ('file', models.FileField(upload_to='', verbose_name='파일')),
            ],
            options={
                'verbose_name': 'Room 명단',
                'verbose_name_plural': 'Room 명단',
                'db_table': 'room',
            },
        ),
    ]
