# Generated by Django 3.2.5 on 2021-08-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='NULL', max_length=128, verbose_name='방 이름')),
                ('email', models.EmailField(default='NULL', max_length=128, verbose_name='아이디')),
                ('app', models.IntegerField(verbose_name='앱 차단 점수')),
                ('person', models.IntegerField(verbose_name='자리 이탈 점수')),
                ('time', models.IntegerField(verbose_name='학습 시간')),
                ('make_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
            options={
                'verbose_name': '집중도',
                'verbose_name_plural': '집중도',
                'db_table': 'analytics',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=128, verbose_name='방 이름')),
                ('room_password', models.CharField(max_length=64, verbose_name='방 비밀번호')),
                ('file', models.FileField(default='NULL', upload_to='room', verbose_name='파일')),
                ('mode', models.CharField(default='NULL', max_length=64, verbose_name='모드')),
                ('maker', models.EmailField(default='NULL', max_length=64, verbose_name='생성자')),
                ('make_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('member_list', models.CharField(default=None, max_length=64, verbose_name='회원명단리스트')),
            ],
            options={
                'verbose_name': 'Room 명단',
                'verbose_name_plural': 'Room 명단',
                'db_table': 'room',
            },
        ),
    ]
