# Generated by Django 3.2.5 on 2021-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='maker',
            field=models.EmailField(default='NULL', max_length=64, verbose_name='생성자'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=128, verbose_name='방 이름'),
        ),
    ]
