# Generated by Django 3.2.5 on 2021-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='email',
            field=models.EmailField(default='NULL', max_length=128, verbose_name='사용자 명단'),
        ),
    ]
