# Generated by Django 3.2.5 on 2021-07-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210729_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mode',
            field=models.CharField(default='NULL', max_length=64, verbose_name='모드'),
        ),
        migrations.AlterField(
            model_name='room',
            name='file',
            field=models.FileField(default='NULL', upload_to='', verbose_name='파일'),
        ),
    ]
