# Generated by Django 3.2.5 on 2021-08-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210812_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='emailList',
        ),
        migrations.AddField(
            model_name='analytics',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='집중도 레벨'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='순위'),
        ),
    ]
