# Generated by Django 2.2.14 on 2021-08-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210730_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='file',
            field=models.FileField(default='NULL', upload_to='room', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
