# Generated by Django 3.2.5 on 2021-08-05 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_room_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='make_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록시간'),
            preserve_default=False,
        ),
    ]
