# Generated by Django 3.2.5 on 2021-08-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210812_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='grade',
            new_name='level',
        ),
    ]
