# Generated by Django 3.2.5 on 2021-08-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_room_make_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('app', models.IntegerField(verbose_name='앱 차단 점수')),
                ('person', models.IntegerField(verbose_name='자리 이탈 점수')),
            ],
            options={
                'verbose_name': '집중도',
                'verbose_name_plural': '집중도',
                'db_table': 'analytics',
            },
        ),
    ]
