# Generated by Django 3.2.5 on 2021-08-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_grade_analytics_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='count',
            field=models.IntegerField(default=0, verbose_name='사용자 수'),
        ),
    ]
