# Generated by Django 3.2.5 on 2021-08-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_analytics_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='app',
            field=models.IntegerField(default=0, verbose_name='앱 차단 점수'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='person',
            field=models.IntegerField(default=0, verbose_name='자리 이탈 점수'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='time',
            field=models.IntegerField(default=0, verbose_name='학습 시간'),
        ),
    ]
