# Generated by Django 3.2.5 on 2021-08-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210810_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='room_name',
            field=models.CharField(default='NULL', max_length=128, verbose_name='방 이름'),
        ),
    ]
