# Generated by Django 3.2.5 on 2021-08-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_analytics_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='member_list',
            field=models.CharField(default=None, max_length=64, verbose_name='회원명단리스트'),
        ),
    ]
